name: BuildAndPack

on:
  push:
    branches:
      - master
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ubuntu-latest:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'StronglyTypedId.sln'

    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true   

      - name: Setup NuGet
        uses: NuGet/setup-nuget@v1.0.5

      - name: Restore dependencies
        run: nuget restore $SOLUTION

      - name: Build
        run: dotnet build $SOLUTION --configuration release --no-restore

      - name: Build
        run: dotnet pack $SOLUTION --configuration release --no-restore

      - name: Publish
        run: 
          nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_TOKEN}}