name: BuildAndPack

on:
  push:
    branches:
      - master
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ubuntu-latest:
    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'StronglyTypedId.sln'
      VERSION: '1.1.1'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $SOLUTION

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x
        include-prerelease: true

    - name: Build
      run: dotnet build $SOLUTION --configuration release -p:Version=$BUILD_VERSION --no-restore