name: BuildAndPack

on:
  push:
    branches:
      - master
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  ubuntu-latest:
    name: ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true      

      - name: Cache .nuke/temp, ~/.nuget/packages
        uses: actions/cache@v2
        with:
          path: |
            .nuke/temp
            ~/.nuget/packages
            !~/.nuget/packages/stronglytypeid
          key: ${{ runner.os }}-${{ hashFiles('**/global.json', '**/*.csproj') }}

      - name: rights
        run: chmod +x ./build.cmd

      - name: rights2
        run: chmod +x ./build.sh

      - name: jopa
        run: ./build.cmd PushToNuGet
        env:
          GithubToken: ${{ secrets.GITHUB_TOKEN }}
          NuGetToken: ${{ secrets.NUGET_TOKEN }}
          MSBuildEnableWorkloadResolver: false
      - uses: actions/upload-artifact@v1
        with:
          name: artifacts
          path: artifacts